### ISSUE TITLE
想詢問本專案是什麼授權

### ISSUE THREAD

**Issue by wildskyf** [shulusama/inviteyoself-g0v#3]
為什麼 http://join.g0v.today/ 不是用這個~~
我覺得這個設計蠻好看的呀 :crying_cat_face:

**Comment by shulusama** [comment]
其實我也不知道耶，之前有用過一陣子然後又換成現在這個了～（因為我不會接XD

**Comment by wildskyf** [comment]
其實應該不是在這邊問吼
我去 g0v/inviteyoself 問問

順便藉這個 issue 來問授權好了XD

**Comment by wildskyf** [comment]
ping @shulusama

**Comment by shulusama** [comment]
授權嗎ＯＡＯ？
本專案授權CC0

**Comment by wildskyf** [comment]
感謝回覆！！
